title: Kranthi Kumar Bitra
theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - dev-sec-ops
  - label: Industrial IoT
    children:
      - industrial-revolution
      - nine-pillars-of-industry-4
      - it-vs-ot-security
      - smart-manufacturing
      - industry-4-readiness
      - iiot-reference-architectures
