title: Tech Pulse
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
baseurl: /tech-pulse
sidebar:
  - label: Cloud Services
    children:
      - cloud-services/aws
      - cloud-services/azure
      - cloud-services/gcp
  - label: DevSecOps
    children:
      - dev-sec-ops/dev-sec-ops
  - label: Industrial IoT
    children:
      - label: Industry 4.0
        children:
          - industry-4.0/industrial-4-revolution
          - industry-4.0/nine-pillars-of-industry-4
          - industry-4.0/it-vs-ot-security
          - industry-4.0/smart-manufacturing
          - industry-4.0/industry-4-readiness
          - industry-4.0/iiot-reference-architectures
      - label: Industry 5.0
        children:
          - industry-5.0/industrial-5-revolution
