title: Tech Pulse
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
baseurl: /tech-pulse
sidebar:
  - label: Cloud Services
    children:
      - cloud-services/aws
      - cloud-services/azure
      - cloud-services/gcp
  - label: DevSecOps
    children:
      - dev-sec-ops/dev-sec-ops
  - label: Industry 4.0
    children:
      - industry-4/industrial-4-revolution
      - industry-4/nine-pillars-of-industry-4
      - industry-4/it-vs-ot-security
      - industry-4/industry-4-readiness
      - industry-4/iiot-reference-architectures
      - industry-4/smart-manufacturing
  - label: Industry 5.0
    children:
      - industry-5/industrial-5-revolution
