title: Tech Pulse
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
baseurl: /tech-pulse
show_sidebar: false
show_navigation: false
hide_zendesk_header: true
hide_zendesk_footer: true
hide_external_links: true