title: Tech Pulse
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
baseurl: /tech-pulse
sidebar:
  - label: Cloud Services
    children:
      - AWS
      - Azure
      - GCP
  - label: DevSecOps
    children:
      - dev-sec-ops
  - label: Industrial IoT
    children:
      - label: Industry 4.0
        children:
          - industrial-4-revolution
          - nine-pillars-of-industry-4
          - it-vs-ot-security
          - smart-manufacturing
          - industry-4-readiness
          - iiot-reference-architectures
      - label: Industry 5.0
        children:
          - industrial-5-revolution
